sites:
  -
    url: https://ipfran.ru
    name: Ipfran
  -
    url: https://dimonvideo.ru
    name: Dimonvideo
  -
    url: https://nikoartgallery.com
    name: Nikoartgallery
  -
    url: https://et-cetera.ru
    name: Et-cetera
  -
    url: https://lutherancathedral.ru
    name: Lutherancathedral
  -
    url: https://dombulgakova.ru
    name: Dombulgakova