spring:
  jpa:
    show-mysql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
sites:
  - url: http://www.playback.ru
    name: Playback
  -
    url: http://radiomv.ru
    name: Radiomv
  -
    url: https://ipfran.ru
    name: Ipfran
  -
    url: https://dimonvideo.ru
    name: Dimonvideo
  -
    url: https://nikoartgallery.com
    name: Nikoartgallery
  -
    url: https://dombulgakova.ru
    name: Dombulgakova
user-agent-name: Search_Engine_App
