spring:
  jpa:
    show-mysql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
user-agent-name: Search_Engine_App
